name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Install Trivy
        run: 
          trivy --version

      
      - name: Build Docker image
        run: docker build -t my-flask-app .

      
      - name: Scan Docker image with Trivy
        run: trivy image --severity CRITICAL,HIGH my-flask-app

      
      - name: Run tests (placeholder)
        run: echo "Test"

