name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.58.1/trivy_0.58.1_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          sudo apt-get install -f

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t my-flask-app .

      # 4. Scan Docker image with Trivy
      - name: Scan Docker image
        run: trivy image --severity CRITICAL,HIGH my-flask-app

      # 5. Run tests (placeholder)
      - name: Run tests (placeholder)
        run: echo "Test"
