
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Install Trivy
        run: | 
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -
                    # Sprawdzanie, gdzie jest zainstalowany trivy
          echo "Trivy installed in: $(pwd)/.trivy/bin"
          # Dodanie ścieżki do zmiennej PATH
          export PATH=$(pwd)/.trivy/bin:$PATH
          # Sprawdzanie wersji Trivy
          trivy --version

      
      - name: Build Docker image
        run: docker build -t my-flask-app .

      
      - name: Scan Docker image with Trivy
        run: trivy image --severity CRITICAL,HIGH my-flask-app

      
      - name: Run tests (placeholder)
        run: echo "Test"

